# Generated by Django 3.2.5 on 2021-07-03 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='telugu_md',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/images')),
                ('vedio', models.CharField(max_length=500)),
                ('cast', models.CharField(max_length=40)),
                ('year', models.IntegerField()),
                ('genre', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('duration', models.CharField(max_length=20)),
            ],
        ),
    ]
