# Generated by Django 3.2.5 on 2021-07-03 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telugu_md',
            name='image',
            field=models.ImageField(null=True, upload_to='media/movie/banner'),
        ),
    ]
