# Generated by Django 3.2.5 on 2021-07-03 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_alter_telugu_md_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telugu_md',
            name='description',
            field=models.TextField(max_length=20),
        ),
    ]
