# Generated by Django 3.2.5 on 2021-07-17 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_alter_telugu_md_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='movies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('banner', models.ImageField(null=True, upload_to='media/movie/banner')),
                ('vedio_link', models.CharField(max_length=500)),
                ('cast', models.CharField(max_length=40)),
                ('year', models.IntegerField()),
                ('genre', models.CharField(max_length=20)),
                ('description', models.TextField(max_length=20)),
                ('duration', models.CharField(max_length=20)),
                ('language', models.CharField(choices=[('telugu', 'telugu'), ('hindi', 'hindi'), ('english', 'english')], max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='telugu_md',
        ),
    ]
