# Generated by Django 3.2.5 on 2021-07-20 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_auto_20210720_1331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='language',
            field=models.CharField(blank=True, choices=[('telugu', 'telugu'), ('hindi', 'hindi'), ('english', 'english')], max_length=20, null=True),
        ),
    ]
