# Generated by Django 3.2.5 on 2021-07-20 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0007_demo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movies',
            name='cast',
        ),
    ]
