# Generated by Django 3.2.5 on 2021-07-22 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0009_add_categories'),
    ]

    operations = [
        migrations.DeleteModel(
            name='demo',
        ),
    ]
