# Generated by Django 3.2.5 on 2021-07-22 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0010_delete_demo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='add_categories',
        ),
    ]
