# Generated by Django 3.2.5 on 2021-07-23 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0012_add_categories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movies',
            name='genre',
        ),
        migrations.AddField(
            model_name='movies',
            name='category',
            field=models.CharField(blank=True, choices=[('movie', 'movie'), ('show', 'show'), ('webseries', 'webseries'), ('Cartoon', 'cartoon')], max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='movies',
            name='geners',
            field=models.CharField(blank=True, choices=[('action', 'action'), ('adventure', 'adventure'), ('comedy', 'comedy'), ('horror', 'horror'), ('thirller', 'thirller'), ('sci fi', 'sci fi')], max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='movies',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('approve', 'approve')], default='pending', max_length=500),
        ),
    ]
