# Generated by Django 3.2.5 on 2021-07-23 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0013_auto_20210723_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='status',
            field=models.CharField(blank=True, choices=[('pending', 'pending'), ('approve', 'approve')], max_length=500, null=True),
        ),
    ]
