# Generated by Django 3.2.5 on 2021-07-23 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0014_alter_movies_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='actor_name',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='movies',
            name='director',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
