# Generated by Django 3.2.5 on 2021-07-27 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0015_auto_20210723_1706'),
    ]

    operations = [
        migrations.DeleteModel(
            name='add_categories',
        ),
        migrations.AlterField(
            model_name='movies',
            name='description',
            field=models.CharField(max_length=1000),
        ),
    ]
