# Generated by Django 3.2.5 on 2021-07-27 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0017_alter_movies_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='main_banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner_image', models.ImageField(null=True, upload_to='static/images')),
            ],
        ),
    ]
