# Generated by Django 3.2.5 on 2021-08-02 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0019_main_banner_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='status',
            field=models.BooleanField(default=0),
        ),
    ]
